name: Build & Deploy
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_CHECKOUT_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: go.sum

      - name: Build
        run: |
          mkdir dist
          GOOS=js GOARCH=wasm go build -v -o dist/is-comment-spam.wasm

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/is-comment-spam.wasm
          fail_on_unmatched_files: true
