# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches: ["main"]
    paths:
      - "*.go"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_CHECKOUT_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: go.sum

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: go-build-cache

      - name: Build
        run: |
          mkdir dist
          GOOS=js GOARCH=wasm go build -v -o dist/is-comment-spam.wasm

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy dist --project-name=is-comment-spam-wasm
